export const SURVIVAL_ITEMS = [
  "Couteau",
  "Couteau à cran d'arrêt",
  "Hache",
  "Machette",
  "Batte de baseball",
  "Batte cloutée",
  "Pied de biche",
  "Bâton",
  "Lance",
  "Arbalète",
  "Arc",
  "Flèches",
  "Pistolet",
  "Revolver",
  "Fusil de chasse",
  "Fusil d’assaut",
  "Mitraillette",
  "Grenade",
  "Cocktail molotov",
  "Bombe artisanale",
  "Bouclier de fortune",
  "Matraque",
  "Massue",
  "Poing américain",
  "Taser",
  "Fronde",
  "Bouteille cassée",
  "Scie",
  "Corde piégée",
  "Lance-pierre",
  "Chaine en métal",
  "Barre à mine",
  "Bombe fumigène",
  "Arc électrique",
  "Shuriken",
  "Épieu",
  "Piquet en bois",
  "Pistolet à plomb",
  "Râteau",
  "Serpe",
  "Couteau suisse",
  "Masque à gaz",
  "Masque tissu",
  "Casque militaire",
  "Casque chantier",
  "Cagoule",
  "Gilet pare-balles",
  "Gilet en cuir",
  "Manteau long",
  "Veste camouflage",
  "Poncho pluie",
  "Pantalon cargo",
  "Bottes",
  "Gants cuir",
  "Lunettes protection",
  "Lunettes nuit",
  "Cape",
  "Protection avant-bras",
  "Genouillères",
  "Écharpe",
  "Bouclier anti-émeute",
  "Cape thermique",
  "Lampe torche",
  "Briquet",
  "Allumettes",
  "Boite d'allume-feu",
  "Bougie",
  "Chandelle",
  "Lampe tempête",
  "Projecteur LED",
  "Bâton lumineux",
  "Pile AA",
  "Pile rechargeable",
  "Batterie portable",
  "Panneau solaire",
  "Dynamo manuelle",
  "Fusée de détresse",
  "Torche à main",
  "Tournevis",
  "Marteau",
  "Scie pliante",
  "Scie sauteuse",
  "Clé à molette",
  "Pinces",
  "Tenaille",
  "Boite à outils",
  "Multi-tool",
  "Lime",
  "Fer à souder",
  "Râpe",
  "Ciseau",
  "Grattoir",
  "Tournevis étoile",
  "Pince coupante",
  "Pied à coulisse",
  "Pelle",
  "Pelle pliante",
  "Pelle US",
  "Corde",
  "Ruban adhésif",
  "Colle forte",
  "Câble acier",
  "Plaque de métal",
  "Élastique solide",
  "Crochet",
  "Filet",
  "Fil de fer",
  "Sangle",
  "Scotch",
  "Gaffeur",
  "Rondin bois",
  "Bouteille d’eau",
  "Gourde",
  "Bidon",
  "Poche à eau",
  "Filtre à eau",
  "Pastilles de purification",
  "Système filtrant",
  "Cuvette",
  "Bassine",
  "Seau",
  "Bassine pliable",
  "Sac d’hydratation",
  "Ration de survie",
  "Conserve",
  "Sachet lyophilisé",
  "Barre énergétique",
  "Viande séchée",
  "Pâtes",
  "Riz",
  "Chocolat",
  "Biscuits secs",
  "Soupe déshydratée",
  "Épices",
  "Sucre",
  "Sel",
  "Miel",
  "Lait en poudre",
  "Boite de sardines",
  "Boîte de thon",
  "Nourriture animale",
  "Trousse de secours",
  "Désinfectant",
  "Bandage",
  "Pansement",
  "Antibiotique",
  "Antalgique",
  "Sérum physiologique",
  "Thermomètre",
  "Gants latex",
  "Ciseaux médicaux",
  "Masque chirurgical",
  "Crème cicatrisante",
  "Bande élastique",
  "Compresse",
  "Cotons-tiges",
  "Préservatif",
  "Pompe à venin",
  "Couverture de survie",
  "Médicaments",
  "Solution hydroalcoolique",
  "Kit d'accouchement",
  "Boussole",
  "Carte papier",
  "Radio",
  "Talkie-walkie",
  "Téléphone satellitaire",
  "Montre à aiguilles",
  "GPS",
  "Carnet étanche",
  "Stylo",
  "Sifflet",
  "Miroir de signalisation",
  "Signal lumineux",
  "Fusée éclairante",
  "Appareil photo jetable",
  "Tente",
  "Tapis de sol",
  "Sac de couchage",
  "Couverture laine",
  "Coussin gonflable",
  "Hamacs",
  "Paracorde",
  "Tarp",
  "Bâche",
  "Matelas mousse",
  "Moustiquaire",
  "Corde à linge",
  "Piquet de tente",
  "Maillet",
  "Brosse à habits",
  "Réchaud gaz",
  "Cartouche gaz",
  "Casserole",
  "Poêle",
  "Gourde métallique",
  "Marmite",
  "Gobelet métal",
  "Spatule",
  "Cuillère",
  "Fourchette",
  "Couteau de table",
  "Bol",
  "Passoire",
  "Planche à découper",
  "Coffret épices",
  "Ouvre-boite",
  "Tire-bouchon",
  "Couteau à pain",
  "Râpe à fromage",
  "Brosse à dents",
  "Dentifrice",
  "Savon",
  "Lingettes",
  "Papier toilette",
  "Brosse cheveux",
  "Peigne",
  "Miroir",
  "Crème solaire",
  "Serviette microfibre",
  "Bâton d’oreille",
  "Ciseaux ongles",
  "Rasoir",
  "Mouchoirs",
  "Baume à lèvres",
  "Fil dentaire",
  "Lotion anti-moustique",
  "Shampooing sec",
  "Déodorant",
  "Capsule iodée",
  "Compteur Geiger",
  "Sac à dos blindé",
  "Lingot d’or",
  "Lingot d’argent",
  "Échantillon ADN",
  "Jeton de troc",
  "Radioactivité badge",
  "Plaquette d’identification",
  "Carte de rationnement",
  "Bombe aérosol défense",
  "Passeport périmé",
  "Journal post-apo",
  "Carte de groupe sanguin",
  "Serre-câble",
  "Lampe frontale",
  "Sac de sable",
  "Plaque d’égout",
  "Cadenas",
  "Clé",
  "Bouchon bouteille",
  "Caisse de munitions",
  "Sac de gravats",
  "Morceau d’os",
  "Pierre à feu",
  "Balle de tennis",
  "Mini-parapluie",
  "Cage piège",
  "Goupille",
  "Dynamite",
  "Lanterne UV",
];

export function randomItem(count = 1) {
  const out = [];
  for (let i = 0; i < count; i++) {
    out.push(SURVIVAL_ITEMS[Math.floor(Math.random()*SURVIVAL_ITEMS.length)]);
  }
  return out;
}
